### PR TITLE
fix: Make the IAM Role name configurable

### PR DESCRIPTION
**Pull request by AndrewCiambrone**
### Summary of Changes

Makes it so that the IAM ROLE name is configurable.

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [X] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [X] PR includes a summary of changes.

### CODE REVIEW

**Review by feng-tao — APPROVED** [review]

**Comment by feng-tao** [comment]
could you fix the DCO?

**Review by friendtocephalopods — APPROVED** [review]
Oops, thanks for the fix!

**Comment by feng-tao** [comment]
thanks @AndrewCiambrone @friendtocephalopods !

**Comment by feng-tao** [comment]
@AndrewCiambrone also do you need a newer version for the lib in order to use it in databuilder?

**Comment by AndrewCiambrone** [comment]
Yeah a new version would be great @feng-tao

**Comment by feng-tao** [comment]
@AndrewCiambrone https://github.com/amundsen-io/amundsengremlin/pull/10

**Pull request merged**
