### PR TITLE
fix IAM role ARN partition fix

### PR DESCRIPTION
**Pull request by jsnowacki**
### Summary of Changes

Fix issue reported in https://github.com/amundsen-io/amundsen/issues/1430 with IAM role ARN not working outside AWS Global. AWS partition is extracted from STS Identity ARN and used to construct IAM role ARN from name.

### CheckList

Make sure you have checked **all** steps below to ensure a timely review.

- [x] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
  - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [x] PR includes a summary of changes.

### CODE REVIEW

**Review by feng-tao — APPROVED** [review]
@jsnowacki  do you think if it is easy to add a test?

**Comment by jsnowacki** [comment]
@feng-tao sorry I was on holidays. While it should be possible, at least to check the ARN itself,  I'm not familiar with the codebase enough I think to incorporate it correctly Nor I know how to mock STS, especially for AWS CN, to do it correctly. Any suggestions? I could add some very artificial magic mock based solution, but it would mostly test string formatting, which is IMO counterproductive. I did check the line of code manually on AWS CN account and it seems to generate correct partition.

**Comment by jsnowacki** [comment]
I've checked moto and it seems to have [hard-coded `aws` partition]( https://github.com/spulec/moto/blob/master/moto/sts/models.py#L51) as well, so using it to test is pointless IMO.

**Comment by feng-tao** [comment]
@jsnowacki could you update the github wf similar to https://github.com/amundsen-io/amundsen/pull/1454? This will fix the license wf issue. thanks

**Comment by jsnowacki** [comment]
@feng-tao Do you mean this changes in `.github/workflows/license.yml`? Do I need also to add the license header everywhere? The error indicates some issues with Go so the workflow changes seem to be needed, but not sure about the license headers.

**Comment by jsnowacki** [comment]
@feng-tao ok the version change seems to do the trick. Thanks!

**Comment by feng-tao** [comment]
thanks!

**Pull request merged**
